version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  configuration: docs/mkdocs.yml

python:
  version: 3.10
  use_system_site_packages: true

requirements_file: docs/requirements.txt

formats: []