
docs_dir: '.'  # replace with the correct path if your documentation files are not in the same directory as mkdocs.yml
site_name: Swarms Documentation
site_url: https://swarms.apac.ai
site_author: Swarms
site_description: Orchestrate Swarms of Agents From Any Framework Like OpenAI, Langchain, and Etc for Real World Workflow Automation.
repo_name: kyegomez/swarms
repo_url: https://github.com/kyegomez/swarms
edit_uri: https://github.com/kyegomez/swarms/tree/main/docs
copyright: TGSC Corp 2024. All rights reserved.


plugins:
  # - glightbox
  - search
  - git-authors
  - mkdocs-jupyter:
        kernel_name: python3
        execute: false
        include_source: True
        include_requirejs: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            parameter_headings: true
            paths: [supervision]
            load_external_modules: true
            allow_inspection: true
            show_bases: true
            group_by_category: true
            docstring_style: google
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_category_heading: true
          domains: [std, py]
  - git-committers:
      repository: kyegomez/swarms
      branch: master
      # token: !ENV ["GITHUB_TOKEN"]
  - git-revision-date-localized:
      enable_creation_date: true
  # - minify_html
  # - redirects
  # - mkdocs-simple-hooks
  # - awesome-pages
  # - mkdocs-versioning
  # # - mkdocs-include-markdown-plugin
  # - enumerate-headings
  # - autolinks

copyright: "&copy; TGSC, Corporation."
extra_css:
  - assets/css/extra.css
extra:
  social:
    - icon: fontawesome/solid/house
      link: assets/img/SwarmsLogoIcon.png
    - icon: fontawesome/brands/discord
      link: https://discord.gg/qUtxnK2NMf
    - icon: fontawesome/brands/github
      link: https://github.com/kyegomez/Swarms/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/Swarms/
theme:
    name: material
    custom_dir: overrides
    logo: assets/img/SwarmsLogoIcon.png
    palette:
      # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - content.code.copy
        - content.code.annotate
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
        - announce.dismiss
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - tables
  - def_list
  - footnotes
nav:
- Home:
    - Overview: "index.md"
    - Install: "install.md"
    - Limitations of Individual Agents: "limits_of_individual_agents.md"
    - Build an Agent: "diy_your_own_agent.md"
    - Build an Agent with tools: "examples/tools_agents.md"
    - Docker Setup: docker_setup.md
- Swarms Cloud API:
  - Overview: "swarms_cloud/main.md"
  - Available Models: "swarms_cloud/available_models.md"
  - Migrate from OpenAI to Swarms in 3 lines of code: "swarms_cloud/migrate_openai.md"
  - Getting Started with SOTA Vision Language Models VLM: "swarms_cloud/getting_started.md"
  - Enterprise Guide to High-Performance Multi-Agent LLM Deployments: "swarms_cloud/production_deployment.md"
- Swarms Framework [PY]:
  - Overview: "swarms/index.md"
  - DIY Build Your Own Agent: "diy_your_own_agent.md"
  - Agents with Tools: "examples/tools_agent.md"
  - swarms.agents:
    - Agents:
      - WorkerAgent: "swarms/agents/workeragent.md"
      - AbstractAgent: "swarms/agents/abstractagent.md"
      - ToolAgent: "swarms/agents/toolagent.md"
  - swarms.models:
    - How to Create A Custom Language Model: "swarms/models/custom_model.md"
    - Deploying Azure OpenAI in Production A Comprehensive Guide: "swarms/models/azure_openai.md"
    - Language:
      - BaseLLM: "swarms/models/base_llm.md"
      - Overview: "swarms/models/index.md"
      - HuggingFaceLLM: "swarms/models/huggingface.md"
      - Anthropic: "swarms/models/anthropic.md"
      - OpenAI: "swarms/models/openai.md"
      - Mistral: "swarms/models/mistral.md"
      - Mixtral: "swarms/models/mixtral.md"
    - MultiModal:
      - BaseMultiModalModel: "swarms/models/base_multimodal_model.md"
      - Fuyu: "swarms/models/fuyu.md"
      - Vilt: "swarms/models/vilt.md"
      - Idefics: "swarms/models/idefics.md"
      - Kosmos: "swarms/models/kosmos.md"
      - Nougat: "swarms/models/nougat.md"
      - Dalle3: "swarms/models/dalle3.md"
      - GPT4V: "swarms/models/gpt4v.md"
      - DistilWhisperModel: "swarms/models/distilled_whisperx.md"
  - swarms.structs:
      - Foundational Structures:
        - Agent: "swarms/structs/agent.md"
        - basestructure: "swarms/structs/basestructure.md"
        - taskinput: "swarms/structs/taskinput.md"
        - stepinput: "swarms/structs/stepinput.md"
        - artifact: "swarms/structs/artifact.md"
        - task: "swarms/structs/task.md"
        - Task Queue Base: "swarms/structs/taskqueuebase.md"
        - YamlModel: "swarms/structs/yaml_model.md"
      - Workflows:
        - recursiveworkflow: "swarms/structs/recursiveworkflow.md"
        - concurrentworkflow: "swarms/structs/concurrentworkflow.md"
        - nonlinearworkflow: "swarms/structs/nonlinearworkflow.md"
        - sequential_workflow: "swarms/structs/sequential_workflow.md"
        - workflow: "swarms/structs/workflow.md"
        - baseworkflow: "swarms/structs/baseworkflow.md"      
      - Multi Agent Architectures:
        - conversation: "swarms/structs/conversation.md"
        - groupchat: "swarms/structs/groupchat.md"
        - swarmnetwork: "swarms/structs/swarmnetwork.md"
        - groupchatmanager: "swarms/structs/groupchatmanager.md"
        - MajorityVoting: "swarms/structs/majorityvoting.md"
  - swarms.memory:
    - Building Custom Vector Memory Databases with the BaseVectorDatabase Class: "swarms/memory/diy_memory.md"
    - ShortTermMemory: "swarms/memory/short_term_memory.md"
- Guides:
    - Building Custom Vector Memory Databases with the BaseVectorDatabase Class: "swarms/memory/diy_memory.md"
    - How to Create A Custom Language Model: "swarms/models/custom_model.md"
    - Deploying Azure OpenAI in Production, A Comprehensive Guide: "swarms/models/azure_openai.md"
    - DIY Build Your Own Agent: "diy_your_own_agent.md"
    - Equipping Autonomous Agents with Tools: "examples/tools_agent.md"
    - Overview: "examples/index.md"
    - Agents:
      - Agent: "examples/flow.md"
      - OmniAgent: "examples/omni_agent.md"
    - Swarms:
      - SequentialWorkflow: "examples/reliable_autonomous_agents.md"
    - 2O+ Autonomous Agent Blogs: "examples/ideas.md"
- Applications:
    - CustomerSupport: 
      - Overview: "applications/customer_support.md"
    - Marketing: 
      - Overview: "applications/marketing_agencies.md" 
    - Swarm of Automated Business Analysis: "applications/business-analyst-agent.md"
- Corporate:
    - Corporate Documents:
      - Data Room: "corporate/data_room.md"
      - The Swarm Memo: "corporate/swarm_memo.md"
      - Corporate Architecture: "corporate/architecture.md"
      - Flywheel: "corporate/flywheel.md"
      - Bounties: "corporate/bounties.md"
      - Purpose: "corporate/purpose.md"
      - Roadmap: "corporate/roadmap.md"
    - Sales:
      - FAQ: "corporate/faq.md"
      - Distribution: "corporate/distribution"
    - Product:
      - SwarmCloud: "corporate/swarm_cloud.md"
      - Weaknesses: "corporate/failures.md"
      - Design: "corporate/design.md"
      - Metric: "corporate/metric.md"
      - Research: "corporate/research.md"
      - Demos: "corporate/demos.md"
      - Checklist: "corporate/checklist.md"
    - Organization:
      - FrontEnd Member Onboarding: "corporate/front_end_contributors.md"
- Contributors:
    - Contributing: "contributing.md"
    - Why Swarms: "why_swarms.md"
    - The Swarms Bounty System: "corporate/swarms_bounty_system.md"    
    
