
name: Lint

on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  yaml-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-go@v4
      - run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - run: yamlfmt .
      - uses: EndBug/add-and-commit@v9
        with:
          message: "yamllint: auto-format"
          default_author: github_actions
  yaml-lint:
    needs: yaml-fmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: yaml Lint
        uses: ibiqlik/action-yamllint@v3
  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8 Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: py-actions/flake8@v2
  ruff-lint:
    runs-on: ubuntu-latest
    name: ruff Lint
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
