---
name: Lint
on: [push, pull_request] # yamllint disable-line rule:truthy
jobs:
  yaml-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - run: yamlfmt .
        # - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install yamllint
      - run: yamllint .
  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8 Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install flake8
      - run: flake8 .
  ruff-lint:
    runs-on: ubuntu-latest
    name: ruff Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install ruff
      - run: ruff format .
      - run: ruff check --fix .
      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
