---
name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/library/setup
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Run Python unit tests
        run: pytest
      - name: Verify that the Docker image for the action builds
        run: docker build . --file Dockerfile
