---
# Notebook-related checks
name: Presubmit checks
on:
  # Relevant PRs
  pull_request:
    paths:
      - "swarms/**"
      - "tests/**"
  # Allow manual runs
  workflow_dispatch:
jobs:
  pytype3_10:
    name: pytype 3.10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/library/setup
      - name: Run pytype
        run: |
          python --version
          pip install .[dev]
          pip install -q gspread ipython
          pytype
  format:
    name: Check format with black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/library/setup
      - name: Check format
        run: |
          python --version
          pip install -q .
          pip install -q black
          black . --check
