---
name: test
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - uses: ./.github/library/setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: pytest
