---
name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/library/setup
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Run Python unit tests
        run: pytest
      - name: Verify that the Docker image for the action builds
        run: docker build . --file Dockerfile
      - name: Verify integration test results
        run: pytest
